package retrieval

import (
	"context"
	"fmt"
	"path/filepath"
	"sync"
	"testing"

	"github.com/jmoiron/sqlx"
	"github.com/srikarjy/biolab-mcp/go-biolab/internal/db"
	"github.com/srikarjy/biolab-mcp/go-biolab/internal/models"
)

// Vectors generated by the Python implementation (biolab.retrieval_log.compute_hash);
// the same values are pinned in tests/test_retrieval_log.py. If either side drifts,
// both suites fail.
const (
	vectorV2     = "90125ef4e394665706600b57ca70dd63192111b5da64520a44db33f1be027a24"
	vectorV1     = "fc3f558ddde4376baba8f9774c9e2ec8b8b2f24ba39d7fcb0e7067b6f725d7cc"
	vectorAnchor = "2ff6a1ddb1b3954331f77c63cfdf37bd666c01d8bc20c40ac2e79c617821db0c"
)

func vectorRecord(version int) models.RetrievalRecord {
	return models.RetrievalRecord{
		RetrievalID: "id-1", Source: "pubmed", ExternalID: "123",
		QueryText:   "BRCA1 \"mut\" <ß> é中 😀 \\ \n\t\x01\x7f",
		RetrievedAt: "2026-01-01T00:00:00+00:00", AgentID: "a&b",
		SourceMetadata: `{"k": "v"}`, RawResponse: "<xml>é</xml>", Snapshot: `{"t":"😀"}`,
		PrevHash: "abc", HashVersion: version,
	}
}

func TestHashMatchesPythonVectors(t *testing.T) {
	for version, want := range map[int]string{2: vectorV2, 1: vectorV1} {
		got, err := ComputeHash(vectorRecord(version))
		if err != nil || got != want {
			t.Fatalf("v%d: got %s (%v), want %s", version, got, err, want)
		}
	}
	if _, err := ComputeHash(vectorRecord(9)); err == nil {
		t.Fatal("unknown version must error")
	}
}

func TestAnchorMACMatchesPython(t *testing.T) {
	a := Anchor{Version: 1, Count: 3, HeadHash: "hé", CreatedAt: "2026-01-01T00:00:00.000000+00:00"}
	if got := anchorMAC(a, []byte("k")); got != vectorAnchor {
		t.Fatalf("got %s want %s", got, vectorAnchor)
	}
}

func newLog(t *testing.T) (*Log, *sqlx.DB) {
	t.Helper()
	database, err := db.Connect(filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatal(err)
	}
	database.SetMaxOpenConns(8)
	l := NewLog(database)
	t.Cleanup(func() { _ = l.Close(); _ = database.Close() })
	return l, database
}

func write(t *testing.T, l *Log, i int) {
	t.Helper()
	rec := BuildRecord(fmt.Sprintf("q%d", i), fmt.Sprintf("%d", i), "agent", "pubmed",
		models.SourceMetadata{}, fmt.Sprintf("raw-%d", i), models.Snapshot{Title: "t"})
	if err := l.Write(context.Background(), rec); err != nil {
		t.Fatal(err)
	}
}

func TestChainVerifiesAndDetectsEveryColumn(t *testing.T) {
	l, database := newLog(t)
	for i := 0; i < 5; i++ {
		write(t, l, i)
	}
	if ok, id, err := VerifyChain(database); err != nil || !ok {
		t.Fatalf("fresh chain should verify: %v %s %v", ok, id, err)
	}
	for _, col := range []string{"source", "external_id", "query_text", "agent_id", "source_metadata", "raw_response", "snapshot", "retrieved_at"} {
		var orig string
		_ = database.Get(&orig, "SELECT "+col+" FROM retrievals ORDER BY rowid LIMIT 1 OFFSET 2")
		_, err := database.Exec("UPDATE retrievals SET " + col + "='tampered' WHERE rowid=(SELECT rowid FROM retrievals ORDER BY rowid LIMIT 1 OFFSET 2)")
		if err != nil {
			t.Fatal(err)
		}
		if ok, _, _ := VerifyChain(database); ok {
			t.Fatalf("tampering %s went undetected", col)
		}
		_, _ = database.Exec("UPDATE retrievals SET "+col+"=? WHERE rowid=(SELECT rowid FROM retrievals ORDER BY rowid LIMIT 1 OFFSET 2)", orig)
		if ok, _, _ := VerifyChain(database); !ok {
			t.Fatalf("restoring %s should verify again", col)
		}
	}
	// Deleting a middle row breaks the link.
	_, _ = database.Exec("DELETE FROM retrievals WHERE rowid=(SELECT rowid FROM retrievals ORDER BY rowid LIMIT 1 OFFSET 1)")
	if ok, _, _ := VerifyChain(database); ok {
		t.Fatal("deleted row went undetected")
	}
}

func TestConcurrentWritersKeepOneLinearChain(t *testing.T) {
	l, database := newLog(t)
	var wg sync.WaitGroup
	for i := 0; i < 40; i++ {
		wg.Add(1)
		go func(i int) { defer wg.Done(); write(t, l, i) }(i)
	}
	wg.Wait()
	ok, id, err := VerifyChain(database)
	if err != nil || !ok {
		t.Fatalf("chain broken under concurrency at %s: %v", id, err)
	}
	var n int
	_ = database.Get(&n, "SELECT count(*) FROM retrievals")
	if n != 40 {
		t.Fatalf("expected 40 rows, got %d", n)
	}
}

func TestAnchorDetectsTruncationAndRewrite(t *testing.T) {
	l, database := newLog(t)
	for i := 0; i < 4; i++ {
		write(t, l, i)
	}
	key := []byte("key")
	a, err := MakeAnchor(database, key)
	if err != nil {
		t.Fatal(err)
	}
	if ok, _, _ := VerifyAnchor(database, a, key); !ok {
		t.Fatal("anchor should verify")
	}
	if ok, _, _ := VerifyAnchor(database, a, []byte("wrong")); ok {
		t.Fatal("wrong key must fail")
	}
	forged := a
	forged.HeadHash = "00"
	if ok, _, _ := VerifyAnchor(database, forged, key); ok {
		t.Fatal("forged head must fail")
	}
	_, _ = database.Exec("DELETE FROM retrievals WHERE rowid=(SELECT max(rowid) FROM retrievals)")
	if ok, _, _ := VerifyChain(database); !ok {
		t.Fatal("tail truncation is invisible to the chain alone")
	}
	if ok, reason, _ := VerifyAnchor(database, a, key); ok {
		t.Fatalf("truncation went undetected: %s", reason)
	}
}

func TestLegacyDatabaseUpgrades(t *testing.T) {
	path := filepath.Join(t.TempDir(), "legacy.db")
	raw := sqlx.MustConnect("sqlite", path)
	raw.MustExec(`CREATE TABLE retrievals (retrieval_id TEXT PRIMARY KEY, source TEXT NOT NULL,
		external_id TEXT NOT NULL, query_text TEXT NOT NULL, retrieved_at TEXT NOT NULL,
		agent_id TEXT NOT NULL, source_metadata TEXT NOT NULL, raw_response TEXT NOT NULL,
		snapshot TEXT NOT NULL, response_hash TEXT NOT NULL)`)
	raw.MustExec(`INSERT INTO retrievals VALUES ('old','pubmed','1','q','t','a','{}','raw','{}','h')`)
	_ = raw.Close()

	database, err := db.Connect(path)
	if err != nil {
		t.Fatal(err)
	}
	defer database.Close()
	var version int
	if err := database.Get(&version, "SELECT hash_version FROM retrievals WHERE retrieval_id='old'"); err != nil || version != 1 {
		t.Fatalf("legacy row should be hash_version 1, got %d (%v)", version, err)
	}
	l := NewLog(database)
	defer l.Close()
	write(t, l, 1) // new writes still work on the upgraded table
}
